[package]
name = "tokio-icmp-echo"
version = "0.4.0"
license = "MIT/Apache-2.0"
authors = ["Fedor Gogolev <knsd@knsd.net>", "Jan Christian Grünhage <jan.christian@gruenhage.xyz"]
documentation = "https://docs.rs/tokio-icmp-echo"
repository = "https://github.com/jcgruenhage/tokio-icmp-echo"
description = "Asynchronous ICMP pinging library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
futures = "0.3"
libc = "0.2"
mio = { version = "0.7", features = ["os-ext"] }
rand = "0.8"
socket2 = { version = "0.4", features = ["all"] }
tokio = { version = "1.5", features = ["rt", "time", "net"] }
parking_lot = "0.11"
thiserror = "1"
async-stream = "0.3"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.5", features = ["rt-multi-thread", "time", "macros"] }
tracing-test = "0.1"

[[example]]
name = "simple"
path = "examples/simple.rs"
